#########################################################
#                   BasicNeeds Config                   #
#########################################################

# World that /spawn will teleport the player to
spawn-world: "world"
# Time in minutes that players will be banned on death
death-ban-time: 15
