#########################################################
#                   BasicNeeds Config                   #
#########################################################

# World that /spawn will teleport the player to
spawn-world: "world"
